import {
  BotIcon,
  BookOpenIcon,
  ClapperboardIcon,
  CreditCardIcon,
  CrosshairIcon,
  FileSearchIcon,
  Gamepad2Icon,
  HammerIcon,
  HeartPulseIcon,
  LayoutDashboardIcon,
  MonitorCogIcon,
  RadioTowerIcon,
  ShieldCheckIcon,
  SparklesIcon,
  TerminalSquareIcon,
  UsersIcon,
  WandSparklesIcon,
} from "lucide-react"

export type HiveAppPlatform = "web" | "mobile" | "service" | "workspace"

export type HiveApp = {
  id: string
  name: string
  repo: string
  platform: HiveAppPlatform
  category: string
  summary: string
  storageScope: string
  command: string
  status: "ready" | "needs-adapter" | "docs-only"
  accent: string
  Icon: typeof MonitorCogIcon
}

export const hiveApps: HiveApp[] = [
  {
    id: "movie-maker",
    name: "KRACKERJACK AI Movie Maker",
    repo: "KRACKERJACK-AI-MOVIE-MAKER-9b5j54",
    platform: "mobile",
    category: "Creator",
    summary: "Expo app for story, book, character, and media workflows.",
    storageScope: "hive/apps/movie-maker",
    command: "npm run web",
    status: "ready",
    accent: "bg-rose-500",
    Icon: ClapperboardIcon,
  },
  {
    id: "movie-maker-root",
    name: "KRACKERJACK Movie Maker Root",
    repo: "KRACKERJACK-AI-MOVIE-MAKER",
    platform: "workspace",
    category: "Creator",
    summary: "Root movie-maker workspace tracked separately from the Expo variant.",
    storageScope: "hive/apps/movie-maker-root",
    command: "see repository README",
    status: "docs-only",
    accent: "bg-pink-700",
    Icon: ClapperboardIcon,
  },
  {
    id: "ai-game-assistant",
    name: "AI Game Assistant",
    repo: "AIGameAssistant",
    platform: "web",
    category: "Automation",
    summary: "Vite assistant for game capture, learning, and automated play.",
    storageScope: "hive/apps/ai-game-assistant",
    command: "npm run dev",
    status: "ready",
    accent: "bg-cyan-500",
    Icon: Gamepad2Icon,
  },
  {
    id: "assimilate-or-die",
    name: "Assimilate Or Die",
    repo: "AssimilateOrDie",
    platform: "mobile",
    category: "Game",
    summary: "Expo game workspace kept separate under the unified Hive shell.",
    storageScope: "hive/apps/assimilate-or-die",
    command: "npm run web",
    status: "ready",
    accent: "bg-lime-500",
    Icon: CrosshairIcon,
  },
  {
    id: "assimilate-or-die-generated",
    name: "Assimilate Or Die 9bhyln",
    repo: "AssimilateOrDie-9bhyln",
    platform: "mobile",
    category: "Game",
    summary: "Generated Expo variant kept as its own Hive app module.",
    storageScope: "hive/apps/assimilate-or-die-9bhyln",
    command: "npm run web",
    status: "ready",
    accent: "bg-yellow-500",
    Icon: CrosshairIcon,
  },
  {
    id: "open-claw-prime",
    name: "OpenClaw Prime",
    repo: "OpenClawPrime",
    platform: "mobile",
    category: "Control",
    summary: "Prime mobile control surface prepared for shared Hive state.",
    storageScope: "hive/apps/open-claw-prime",
    command: "npm run web",
    status: "ready",
    accent: "bg-orange-500",
    Icon: HammerIcon,
  },
  {
    id: "luna-companion",
    name: "Luna Companion",
    repo: "LunaCompanion",
    platform: "mobile",
    category: "Companion",
    summary: "Companion app with its own workspace and Hive memory lane.",
    storageScope: "hive/apps/luna-companion",
    command: "npm run web",
    status: "ready",
    accent: "bg-fuchsia-500",
    Icon: SparklesIcon,
  },
  {
    id: "freq-board-sleuth",
    name: "FreqBoard Sleuth",
    repo: "FreqBoardSleuth",
    platform: "mobile",
    category: "Intel",
    summary: "Frequency board investigation app registered in the Hive.",
    storageScope: "hive/apps/freq-board-sleuth",
    command: "npm run web",
    status: "ready",
    accent: "bg-amber-500",
    Icon: RadioTowerIcon,
  },
  {
    id: "grok-schitt",
    name: "GROKSCHITT",
    repo: "GROKSCHITT",
    platform: "web",
    category: "AI",
    summary: "Vite AI workspace mounted as a standalone Hive app.",
    storageScope: "hive/apps/grok-schitt",
    command: "npm run dev",
    status: "ready",
    accent: "bg-violet-500",
    Icon: WandSparklesIcon,
  },
  {
    id: "neural-shield",
    name: "NeuralShield",
    repo: "NeuralShield",
    platform: "web",
    category: "Security",
    summary: "Security app workspace connected through shared Hive metadata.",
    storageScope: "hive/apps/neural-shield",
    command: "npm run dev",
    status: "ready",
    accent: "bg-emerald-500",
    Icon: ShieldCheckIcon,
  },
  {
    id: "universal-reader",
    name: "UniversalReader",
    repo: "UniversalReader",
    platform: "mobile",
    category: "Reader",
    summary: "Reader app available as a separate Hive module.",
    storageScope: "hive/apps/universal-reader",
    command: "npm run web",
    status: "ready",
    accent: "bg-blue-500",
    Icon: BookOpenIcon,
  },
  {
    id: "scam-shield",
    name: "Scam Shield AI",
    repo: "SCAM-SHIELD-AND-SCAM-SHIELD-AI-COMBINED-UPDATE-FIX-FUKUP",
    platform: "web",
    category: "Security",
    summary: "Next security portal staged for shared Hive storage.",
    storageScope: "hive/apps/scam-shield",
    command: "npm run dev",
    status: "ready",
    accent: "bg-red-500",
    Icon: HeartPulseIcon,
  },
  {
    id: "onspace",
    name: "OnSpace 9b5tbh",
    repo: "onspace-9b5tbh-10560",
    platform: "web",
    category: "Builder",
    summary: "Vite OnSpace app builder workspace registered in the Hive.",
    storageScope: "hive/apps/onspace-9b5tbh-10560",
    command: "npm run dev",
    status: "ready",
    accent: "bg-sky-500",
    Icon: SparklesIcon,
  },
  {
    id: "radix-nova",
    name: "Radix Nova Hive Shell",
    repo: "v0-new-radix-nova-project",
    platform: "web",
    category: "Core",
    summary: "Current Next main app that hosts the unified Hive catalog.",
    storageScope: "hive/apps/radix-nova-shell",
    command: "npm run dev",
    status: "ready",
    accent: "bg-zinc-950",
    Icon: LayoutDashboardIcon,
  },
  {
    id: "cash-app-payment-portal",
    name: "Cash App Payment Portal",
    repo: "CashAppPaymentPortal",
    platform: "mobile",
    category: "Finance",
    summary: "Payment portal isolated as its own Hive app workspace.",
    storageScope: "hive/apps/cash-app-payment-portal",
    command: "npm run web",
    status: "ready",
    accent: "bg-green-500",
    Icon: CreditCardIcon,
  },
  {
    id: "kingshot-discord-bot",
    name: "Kingshot Discord Bot",
    repo: "Kingshot-Discord-Bot",
    platform: "service",
    category: "Bot",
    summary: "Discord bot tracked in Hive as a service module.",
    storageScope: "hive/apps/kingshot-discord-bot",
    command: "see repository README",
    status: "needs-adapter",
    accent: "bg-indigo-500",
    Icon: BotIcon,
  },
  {
    id: "hunter-prime",
    name: "HunterPrime",
    repo: "HunterPrime",
    platform: "workspace",
    category: "Intel",
    summary: "HunterPrime workspace registered for future app/runtime adapter work.",
    storageScope: "hive/apps/hunter-prime",
    command: "see repository README",
    status: "docs-only",
    accent: "bg-neutral-700",
    Icon: FileSearchIcon,
  },
  {
    id: "kingshot-redeemer",
    name: "Kingshot Redeemer",
    repo: "KingshotRedeemer",
    platform: "service",
    category: "Bot",
    summary: "Redeemer service registered for a future runtime adapter.",
    storageScope: "hive/apps/kingshot-redeemer",
    command: "see repository README",
    status: "needs-adapter",
    accent: "bg-teal-500",
    Icon: UsersIcon,
  },
  {
    id: "hive-os",
    name: "THE HIVE OS",
    repo: "THE-HIVE-OS",
    platform: "workspace",
    category: "Core",
    summary: "Sovereign root workspace and storage identity for all apps.",
    storageScope: "hive/core",
    command: "main shell",
    status: "docs-only",
    accent: "bg-zinc-800",
    Icon: MonitorCogIcon,
  },
  {
    id: "tools",
    name: "Savage Army Tools",
    repo: "GROK-SAVAGE-ARMY-K377-TOOLS",
    platform: "workspace",
    category: "Tools",
    summary: "Repository toolset tracked as a Hive workspace.",
    storageScope: "hive/apps/savage-army-tools",
    command: "see repository README",
    status: "docs-only",
    accent: "bg-slate-600",
    Icon: TerminalSquareIcon,
  },
  {
    id: "reader-intel",
    name: "MCGILLICUDDY",
    repo: "MCGILLICUDDY",
    platform: "workspace",
    category: "Intel",
    summary: "Documentation workspace available from the Hive catalog.",
    storageScope: "hive/apps/mcgillicuddy",
    command: "see repository README",
    status: "docs-only",
    accent: "bg-stone-600",
    Icon: FileSearchIcon,
  },
]

export const hiveTotals = {
  apps: hiveApps.length,
  ready: hiveApps.filter((app) => app.status === "ready").length,
  services: hiveApps.filter((app) => app.platform === "service").length,
  storageScopes: new Set(hiveApps.map((app) => app.storageScope)).size,
}
