/**
 * HIVE_CORE / refinery.js
 *  - "Memory Refinery"  - self-evolution / upstream fallback
 *  - tries to pull upstream updates; if upstream fails, generates custom
 *    package mirror / patch notes for the Hive
 *  - keeps a tamper-evident digest chain of every change (no claims of
 *    bypassing host OS - this is HIVE-level bookkeeping only)
 */
'use strict';
const fs   = require('fs');
const path = require('path');
const crypto = require('crypto');
const os   = require('os');
const https = require('https');

const identity = require('./identity');
const role     = require('./role-engine');

const STATE_PATH = path.join(identity.HIVE_HOME, 'refinery.json');
const LOG_PATH   = path.join(identity.HIVE_HOME, 'logs', 'refinery.log');

function loadState() {
  try { return JSON.parse(fs.readFileSync(STATE_PATH, 'utf8')); }
  catch (_) { return { chain: [], last_upstream_attempt: null, last_success: null, custom_patches: [] }; }
}
function saveState(s) {
  fs.mkdirSync(path.dirname(STATE_PATH), { recursive: true });
  fs.writeFileSync(STATE_PATH, JSON.stringify(s, null, 2));
}
function logLine(line) {
  fs.mkdirSync(path.dirname(LOG_PATH), { recursive: true });
  fs.appendFileSync(LOG_PATH, `${new Date().toISOString()}\t${line}\n`);
}
function digest(s) { return crypto.createHash('sha256').update(JSON.stringify(s)).digest('hex'); }

function appendEntry(kind, payload) {
  const s = loadState();
  const prev = s.chain.length ? s.chain[s.chain.length - 1].digest : 'GENESIS';
  const entry = { ts: new Date().toISOString(), kind, payload, prev };
  entry.digest = digest({ prev, ...entry });
  s.chain.push(entry);
  if (s.chain.length > 1000) s.chain = s.chain.slice(-1000);
  saveState(s);
  logLine(`${kind} ${entry.digest.slice(0, 12)}`);
  return entry;
}

function fetchUrl(u, timeoutMs = 8000) {
  return new Promise((resolve, reject) => {
    const url = new URL(u);
    if (!/^https:$/.test(url.protocol)) return reject(new Error('https only'));
    const req = https.get(url, { timeout: timeoutMs, headers: { 'User-Agent': 'HIVE-Refinery/1.0' } }, res => {
      let data = ''; res.on('data', c => { data += c; if (data.length > 200000) data = data.slice(0, 200000) + '...'; });
      res.on('end', () => resolve({ status: res.statusCode, body: data }));
    });
    req.on('error', reject);
    req.on('timeout', () => req.destroy(new Error('timeout')));
  });
}

async function checkUpstream(sources) {
  // sources: array of https urls to probe
  const st = loadState();
  st.last_upstream_attempt = new Date().toISOString();
  const probes = [];
  for (const u of sources || []) {
    try {
      const r = await fetchUrl(u, 5000);
      probes.push({ url: u, status: r.status, ok: r.status >= 200 && r.status < 400 });
    } catch (e) {
      probes.push({ url: u, ok: false, err: e.message });
    }
  }
  saveState(st);
  return probes;
}

function buildCustomPatch({ name, version, base, note }) {
  // Synthesize a "custom update" record the Hive can ship even when upstream is dead
  const patch = {
    name,
    version,
    base,
    note: note || 'Custom patch generated by HIVE Refinery.',
    artifact_uri: `hive://refinery/${name}/${version}`,
    generated_at: new Date().toISOString(),
  };
  const s = loadState();
  s.custom_patches.push(patch);
  if (s.custom_patches.length > 200) s.custom_patches = s.custom_patches.slice(-200);
  saveState(s);
  appendEntry('refinery.custom_patch', patch);
  return patch;
}

function verify() {
  const s = loadState();
  let ok = true;
  for (let i = 0; i < s.chain.length; i++) {
    const e = s.chain[i];
    const expected = digest({ prev: e.prev, ts: e.ts, kind: e.kind, payload: e.payload });
    if (expected !== e.digest) { ok = false; appendEntry('refinery.verify', { index: i, ok: false }); break; }
  }
  return { ok, length: s.chain.length };
}

function run({ sources = [] } = {}) {
  // role gate
  try { role.requireCap('system.update'); } catch (e) { return { error: e.message }; }
  return checkUpstream(sources).then(probes => {
    const anyOk = probes.some(p => p.ok);
    if (!anyOk && sources.length) {
      // upstream failing -> synthesize a custom update
      const id = identity.read() || {};
      const patch = buildCustomPatch({
        name: 'hive-core',
        version: identity.VERSION,
        base: id.base || os.platform(),
        note: 'Upstream unreachable. Custom evolution patch generated by the Refinery.',
      });
      appendEntry('refinery.upstream_fail', { sources, patch });
      return { probes, fallback: 'custom', patch };
    }
    const s = loadState();
    s.last_success = new Date().toISOString();
    saveState(s);
    appendEntry('refinery.upstream_ok', { sources });
    return { probes, fallback: 'none' };
  });
}

module.exports = { run, checkUpstream, buildCustomPatch, verify, appendEntry, STATE_PATH };

if (require.main === module) {
  const cmd = process.argv[2] || 'run';
  if (cmd === 'run') {
    const sources = process.argv.slice(3);
    run({ sources }).then(r => process.stdout.write(JSON.stringify(r, null, 2) + '\n'));
  } else if (cmd === 'verify') {
    process.stdout.write(JSON.stringify(verify(), null, 2) + '\n');
  } else if (cmd === 'chain') {
    const s = loadState();
    process.stdout.write(JSON.stringify(s.chain.slice(-20), null, 2) + '\n');
  } else if (cmd === 'patch') {
    const args = require('minimist')(process.argv.slice(3));
    const p = buildCustomPatch({ name: args.name, version: args.version, base: args.base, note: args.note });
    process.stdout.write(JSON.stringify(p, null, 2) + '\n');
  } else {
    process.stderr.write('usage: refinery.js [run [urls...]|verify|chain|patch --name --version --base --note]\n');
    process.exit(2);
  }
}
